### ISSUE TITLE
Maintained?

### ISSUE THREAD

**Issue by adsick** [mana-lang/mana#1]
Hi, I'd like to name my project "mana", but the name appears to be taken on crates.io by this project, which is updated 2 years ago. Is it possible that you pass me the ownership of this name?

**Comment by tommywalkie** [comment]
Hi @adsick , sure thing! I'll ping you shortly by email once available this week so I can give you the details 👍

**Comment by adsick** [comment]
that sounds great!

**Comment by tommywalkie** [comment]
Hi @adsick, sorry for the delay, looks like the steps are easier since the last time I did it two years ago, I'll just need your Cargo username, can you confirm that you're using [this one profile](https://crates.io/users/adsick)? 🙏

**Comment by adsick** [comment]
Yes, I use this profile.
